"""Agregamos tabla categoria

Revision ID: 2099f6743720
Revises: 
Create Date: 2025-08-02 15:18:59.591932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2099f6743720'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('instalacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'category', ['categoria'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repuesto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('categoria',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('instalacion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'repuesto', ['precio'], ['precio'])

    op.drop_table('category')
    # ### end Alembic commands ###
