"""permitirt categorias iguales en diferemtes usuarios

Revision ID: c83c4e1ebe50
Revises: fa1652313d14
Create Date: 2025-08-05 06:40:18.061950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83c4e1ebe50'
down_revision = 'fa1652313d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_category_per_user', ['nombre', 'usuario_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('unique_category_per_user', type_='unique')

    # ### end Alembic commands ###
